In [72]:
%pip install mediapipe opencv-python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
        



Note: you may need to restart the kernel to use updated packages.


In [73]:
# ignore warnings
import warnings
warnings.filterwarnings("ignore")

# Read Training Data

In [74]:

path = r'C:\Users\henri\Documents\FingerCounterData\DatasetForFingerCounter'
training_path = path + r'\training_landmarks.csv'
training_path
# Write the DataFrame to a CSV file
df = pd.read_csv(training_path)



In [75]:
X_train = df[['x0','y0','z0','x1','y1','z1','x2','y2','z2','x3','y3','z3','x4','y4','z4','x5','y5','z5','x6','y6','z6','x7','y7','z7','x8','y8','z8','x9','y9','z9','x10','y10','z10','x11','y11','z11','x12','y12','z12','x13','y13','z13','x14','y14','z14','x15','y15','z15','x16','y16','z16','x17','y17','z17','x18','y18','z18','x19','y19','z19','x20','y20','z20']]
y_train = df['image']
y_train = y_train.map(lambda image: image.split('_')[2])

# Build and Train Model

In [76]:
# build the lightgbm model
import lightgbm as lgb
#clf = lgb.LGBMClassifier()
#clf.fit(X_train, y_train)

# Read Test Data

In [77]:
path = r'C:\Users\henri\Documents\FingerCounterData\DatasetForFingerCounter'
training_path = path + r'\test_landmarks.csv'
# Write the DataFrame to a CSV file
df = pd.read_csv(training_path)

In [78]:
X_test = df[['x0','y0','z0','x1','y1','z1','x2','y2','z2','x3','y3','z3','x4','y4','z4','x5','y5','z5','x6','y6','z6','x7','y7','z7','x8','y8','z8','x9','y9','z9','x10','y10','z10','x11','y11','z11','x12','y12','z12','x13','y13','z13','x14','y14','z14','x15','y15','z15','x16','y16','z16','x17','y17','z17','x18','y18','z18','x19','y19','z19','x20','y20','z20']]
y_test = df['image']
y_test = y_test.map(lambda image: image.split('_')[2])

# Measurements and Accuracy

## Test best num_leaves

In [97]:
# build the lightgbm model
data = []
import lightgbm as lgb
for i in range(2,100):
    clf = lgb.LGBMClassifier(num_leaves=i,verbose=-1)
    clf.fit(X_train, y_train)
    y_pred=clf.predict(X_test)
    data.append([i,clf.score(X_test, y_test)])
    print(i)
    print('Test set score: {:.4f}'.format(clf.score(X_test, y_test)))
print("highest score:")    
print(max(data, key=lambda x:x[1]))

2
Test set score: 0.7225
3
Test set score: 0.8325
4
Test set score: 0.8586
5
Test set score: 0.8743
6
Test set score: 0.8639
7
Test set score: 0.9005
8
Test set score: 0.9058
9
Test set score: 0.9005
10
Test set score: 0.9162
11
Test set score: 0.9005
12
Test set score: 0.9058
13
Test set score: 0.9058
14
Test set score: 0.9110
15
Test set score: 0.9058
16
Test set score: 0.9058
17
Test set score: 0.9110
18
Test set score: 0.9162
19
Test set score: 0.9058
20
Test set score: 0.9110
21
Test set score: 0.9058
22
Test set score: 0.9058
23
Test set score: 0.9005
24
Test set score: 0.9005
25
Test set score: 0.9005
26
Test set score: 0.9110
27
Test set score: 0.8953
28
Test set score: 0.9005
29
Test set score: 0.8953
30
Test set score: 0.8953
31
Test set score: 0.9005
32
Test set score: 0.9110
33
Test set score: 0.9005
34
Test set score: 0.8953
35
Test set score: 0.9058
36
Test set score: 0.8953
37
Test set score: 0.9005
38
Test set score: 0.8901
39
Test set score: 0.8901
40
Test set score: 0

KeyboardInterrupt: 

### Best num_leaves = 10!

## Test best learning_rate

In [94]:
# build the lightgbm model
data = []
import lightgbm as lgb
for i in range(1,10):
    clf = lgb.LGBMClassifier(num_leaves=10,verbose=-1, learning_rate=i/10)
    clf.fit(X_train, y_train)
    y_pred=clf.predict(X_test)
    data.append([i,clf.score(X_test, y_test)])
    print(i)
    print('Test set score: {:.4f}'.format(clf.score(X_test, y_test)))
print("highest score:")    
print(max(data, key=lambda x:x[1]))

1
Test set score: 0.9162
2
Test set score: 0.9110
3
Test set score: 0.9058
4
Test set score: 0.8953
5
Test set score: 0.9110
6
Test set score: 0.8953
7
Test set score: 0.8953
8
Test set score: 0.9005
9
Test set score: 0.1885
highest score:
[1, 0.9162303664921466]


### Best learning_rate = 0.1 => default!

## Test best max_depth

In [99]:
# build the lightgbm model
data = []
import lightgbm as lgb
for i in range(-1,100):
    clf = lgb.LGBMClassifier(num_leaves=10,verbose=-1,max_depth=i)
    clf.fit(X_train, y_train)
    y_pred=clf.predict(X_test)
    data.append([i,clf.score(X_test, y_test)])
    print(i)
    print('Test set score: {:.4f}'.format(clf.score(X_test, y_test)))
print("highest score:")    
print(max(data, key=lambda x:x[1]))

-1
Test set score: 0.9162
0
Test set score: 0.9162
1
Test set score: 0.7225
2
Test set score: 0.8639
3
Test set score: 0.8848
4
Test set score: 0.8796
5
Test set score: 0.9110
6
Test set score: 0.9058
7
Test set score: 0.9110
8
Test set score: 0.9110
9
Test set score: 0.9162
10
Test set score: 0.9162
11
Test set score: 0.9162
12
Test set score: 0.9162
13
Test set score: 0.9162
14
Test set score: 0.9162
15
Test set score: 0.9162
16
Test set score: 0.9162
17
Test set score: 0.9162
18
Test set score: 0.9162
19
Test set score: 0.9162
20
Test set score: 0.9162
21
Test set score: 0.9162
22
Test set score: 0.9162
23
Test set score: 0.9162
24
Test set score: 0.9162
25
Test set score: 0.9162
26
Test set score: 0.9162
27
Test set score: 0.9162
28
Test set score: 0.9162
29
Test set score: 0.9162
30
Test set score: 0.9162
31
Test set score: 0.9162
32
Test set score: 0.9162
33
Test set score: 0.9162
34
Test set score: 0.9162
35
Test set score: 0.9162
36
Test set score: 0.9162
37
Test set score: 0.9

### Best max_depth = -1 => default!

## Test best min_data_in_leaf

In [100]:
# build the lightgbm model
data = []
import lightgbm as lgb
for i in range(1,100):
    clf = lgb.LGBMClassifier(num_leaves=10,verbose=-1,min_data_in_leaf=i)
    clf.fit(X_train, y_train)
    y_pred=clf.predict(X_test)
    data.append([i,clf.score(X_test, y_test)])
    print(i)
    print('Test set score: {:.4f}'.format(clf.score(X_test, y_test)))
print("highest score:")    
print(max(data, key=lambda x:x[1]))

1
Test set score: 0.9110
2
Test set score: 0.8953
3
Test set score: 0.9162
4
Test set score: 0.9058
5
Test set score: 0.9162
6
Test set score: 0.9005
7
Test set score: 0.9005
8
Test set score: 0.9162
9
Test set score: 0.8953
10
Test set score: 0.9110
11
Test set score: 0.9005
12
Test set score: 0.9267
13
Test set score: 0.9058
14
Test set score: 0.9058
15
Test set score: 0.8901
16
Test set score: 0.9110
17
Test set score: 0.9110
18
Test set score: 0.9058
19
Test set score: 0.8901
20
Test set score: 0.9162
21
Test set score: 0.9005
22
Test set score: 0.9058
23
Test set score: 0.8953
24
Test set score: 0.8953
25
Test set score: 0.9005
26
Test set score: 0.8953
27
Test set score: 0.9110
28
Test set score: 0.8953
29
Test set score: 0.9110
30
Test set score: 0.8953
31
Test set score: 0.9005
32
Test set score: 0.9005
33
Test set score: 0.8901
34
Test set score: 0.8901
35
Test set score: 0.9005
36
Test set score: 0.9110
37
Test set score: 0.9005
38
Test set score: 0.9110
39
Test set score: 0.

### Best min_data_in_leaf = 12!

## Test best min_sum_heassian_in_leaf

In [101]:
# build the lightgbm model
data = []
import lightgbm as lgb
for i in range(1,100):
    clf = lgb.LGBMClassifier(num_leaves=10,verbose=-1,min_data_in_leaf=12,min_sum_hessian_in_leaf=i/100)
    clf.fit(X_train, y_train)
    y_pred=clf.predict(X_test)
    data.append([i,clf.score(X_test, y_test)])
    print(i)
    print('Test set score: {:.4f}'.format(clf.score(X_test, y_test)))
print("highest score:")    
print(max(data, key=lambda x:x[1]))

1
Test set score: 0.9267
2
Test set score: 0.9267
3
Test set score: 0.9162
4
Test set score: 0.9267
5
Test set score: 0.9110
6
Test set score: 0.9267
7
Test set score: 0.9110
8
Test set score: 0.9058
9
Test set score: 0.8953
10
Test set score: 0.9110
11
Test set score: 0.9058
12
Test set score: 0.9162
13
Test set score: 0.9162
14
Test set score: 0.9058
15
Test set score: 0.9058
16
Test set score: 0.8953
17
Test set score: 0.9005
18
Test set score: 0.9005
19
Test set score: 0.9058
20
Test set score: 0.9058
21
Test set score: 0.8953
22
Test set score: 0.9058
23
Test set score: 0.9110
24
Test set score: 0.9110
25
Test set score: 0.9058
26
Test set score: 0.9162
27
Test set score: 0.9162
28
Test set score: 0.9058
29
Test set score: 0.9110
30
Test set score: 0.9215
31
Test set score: 0.9110
32
Test set score: 0.9058
33
Test set score: 0.9110
34
Test set score: 0.9110
35
Test set score: 0.9058
36
Test set score: 0.9005
37
Test set score: 0.8953
38
Test set score: 0.9058
39
Test set score: 0.

### Best min_sum_hessian_in_leaf = 0.001 => default!

## Test best 

In [80]:
# predict the results
y_pred=clf.predict(X_test)

# view accuracy
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_pred, y_test)
#print('LightGBM Model accuracy score: {0:0.4f}'.format(accuracy_score(y_test, y_pred)))

In [81]:
y_pred_train = clf.predict(X_train)
print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))

Training-set accuracy score: 1.0000


In [82]:
# print the scores on training and test set

print('Training set score: {:.4f}'.format(clf.score(X_train, y_train)))

print('Test set score: {:.4f}'.format(clf.score(X_test, y_test)))

Training set score: 1.0000
Test set score: 0.8901


In [83]:
# view confusion-matrix
# Print the Confusion Matrix and slice it into four pieces

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix\n\n', cm)
print('\nTrue Positives(TP) = ', cm[0,0])
print('\nTrue Negatives(TN) = ', cm[1,1])
print('\nFalse Positives(FP) = ', cm[0,1])
print('\nFalse Negatives(FN) = ', cm[1,0])

Confusion matrix

 [[21  2  1  5  0  0  0]
 [ 0 27  2  0  1  1  0]
 [ 0  0 23  0  0  0  0]
 [ 1  2  0 31  0  0  1]
 [ 0  1  0  0 25  2  0]
 [ 1  0  0  0  0 20  0]
 [ 0  0  1  0  0  0 23]]

True Positives(TP) =  21

True Negatives(TN) =  27

False Positives(FP) =  2

False Negatives(FN) =  0


In [84]:
import cv2
import mediapipe as mp

# Initialisieren von MediaPipe und Hands
mp_hands = mp.solutions.hands
mp_drawing = mp.solutions.drawing_utils
hands = mp_hands.Hands(min_detection_confidence=0.8, min_tracking_confidence=0.5)

# Pfad zum Bild auf Ihrer Festplatte
image_path = "C:/Users/henri/Documents/testData/image_spock_13.jpg" #add your path

# Bild einlesen
image = cv2.imread(image_path)

# BGR 2 RGB
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Detections
with hands:
    results = hands.process(image_rgb)
    
# Extrahieren der Koordinaten der Handlandmarken
landmark_coords = {}
if results.multi_hand_landmarks:
    for i, landmark in enumerate(results.multi_hand_landmarks[0].landmark):
        landmark_coords[f'x{i+1}'] = landmark.x
        landmark_coords[f'y{i+1}'] = landmark.y
        landmark_coords[f'z{i+1}'] = landmark.z

    # Ausgabe der Koordinaten


    # Erstellen eines Pandas DataFrame aus dem Dictionary
    df = pd.DataFrame([landmark_coords])


    y_pred=clf.predict(df)
    print(y_pred)
else:
    print('no hand detected')

['one']
